# .github/workflows/build-tsplib.yml
name: Build TSPLIB JSON
on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 2 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install --upgrade pip
          pip install requests tsplib95
      - run: python scripts/build_tsplib_json.py
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/tsplib.json docs/data/tsplib.json || true
          if git diff --cached --quiet; then echo "No changes."; else git commit -m "build: update TSPLIB JSON"; git push; fi
