# .github/workflows/build-tsplib.yml
name: Build TSPLIB JSON

on:
  workflow_dispatch: {}
  schedule:
    - cron: "17 2 * * *"  # 매일 11:17 KST (02:17 UTC) 정도

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # GITHUB_TOKEN으로 커밋
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests tsplib95

      - name: Build tsplib.json
        run: |
          python scripts/build_tsplib_json.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/tsplib.json
          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "build: update TSPLIB JSON"
            git push
          fi
